export let eventArray = [
  {
    id: 0,
    name: "Wallace James",
    location: "Abuja, Nigeria",
    date: "03 JUNE",
    title: `The next confrence 23'`,
    price: "$10.00",
    image: "image 15",
    mapline: "MapPinLine",
    icon: "eventcreator_3",
  },

  {
    id: 1,
    name: "Mirable Kalu",
    location: "Uyo, Nigeria",
    date: "03 JUNE",
    title: "Devfest",
    price: "FREE",
    image: "event_image4",
    mapline: "MapPinLine",
    icon: "eventcreator_1",
  },

  {
    id: 2,
    name: "Annabel Richard",
    location: "Lagos, Nigeria",
    date: "03 JUNE",
    title: "Sip and Pant NG at RadisonBlu",
    price: "FREE",
    image: "event_image3",
    mapline: "MapPinLine",
    icon: "eventcreator_2",
  },
  {
    id: 3,
    name: "Wallace James",
    location: "Lagos",
    date: "03 JUNE",
    title: "Goalfest 2023",
    price: "$10.00",
    image: "event_image2",
    mapline: "MapPinLine",
    icon: "eventcreator_3",
  },
  {
    id: 4,
    name: "Wallace James",
    location: "Lagos",
    date: "03 JUNE",
    title: "Swimming Trainings",
    image: "event_image3",
    price: "FREE",
    mapline: "MapPinLine",
    image: "event_image1",
    icon: "eventcreator_3",
  },
];
